spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community_db
    username: root
    password: 123
  jackson:
#    date-format: com.fasterxml.jackson.databind.util.StdDateFormat


server:
  servlet:
    encoding:
      charset: utf-8


