spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community_db
    username: root
    password: 123
  jackson:
#tomcat

    #mail properties
  mail:
    host: smtp.126.com
    port: 465
    username: handwasherhan@126.com
    password: WYVMNUHOJEWZXACF
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: localhost
    port: 6379
    database: 0
#    date-format: com.fasterxml.jackson.databind.util.StdDateFormat


server:
  servlet:
    encoding:
      charset: utf-8
  port: 9090

